<script lang="ts">
	import { slide, fade } from 'svelte/transition';
	import { resolve } from '$app/paths';
	import hero_img from '$lib/assets/solar-hero.webp';
	import { zamfara, taj, crown_club, glisten, jaiz } from '$lib/assets/partners';
	import {
		crown_club_project,
		mowa_zamfara,
		mowa_zamfara2,
		glistens_project,
		great_height,
		taj_bank_kano,
		taj_bank_sokoto,
		lakeview_estate,
		edible_creations
	} from '$lib/assets/projects';
	type FAQ = {
		question: string;
		answer: string;
	};

	const faqs: FAQ[] = [
		{
			question: 'What are the challenges of renewable energy?',
			answer: `One of the primary challenges is intermittency, as solar and wind power generation are dependent on weather conditions, making it difficult to ensure a stable and reliable energy supply. Individuals can take several steps to reduce the challenges to solar energy, particularly those related to weather. For instance, installing a battery storage system can help store excess energy generated during sunny periods for use during cloudy or nighttime periods. Additionally, investing in a solar panel cleaning system can help maintain the efficiency of the panels by removing dirt and debris. Individuals can also consider installing solar panels with a high efficiency rating or those designed to perform well in low-light conditions. Furthermore, individuals can optimize their energy usage by shifting non-essential loads to sunny periods, such as running washing machines or dishwashers during the day. By taking these steps, individuals can help mitigate the impact of weather-related challenges on their solar energy systems.`
		},
		{
			question: 'What are the benefits of solar energy?',
			answer: `The benefits of solar energy include:\n
- Renewable and sustainable energy source\n
- Zero greenhouse gas emissions or pollution\n
- Energy independence and reduced reliance on grid electricity\n
- Lower energy bills and cost savings\n
- Increased property value`
		},
		{
			question: 'How long do solar panels last?',
			answer: `Solar panels are designed to last for many years, typically between 25 to 30 years or more. Most solar panel manufacturers offer a warranty of 25 years or more, guaranteeing that the panels will retain a certain level of efficiency over time.`
		},
		{
			question: `Do solar panels work on cloudy days?`,
			answer: `Yes, solar panels can still generate electricity on cloudy days, although at a reduced capacity. Solar panels convert sunlight into electricity, and while cloud cover can reduce the amount of sunlight available, it’s still possible to generate some electricity.`
		},
		{
			question: 'Can I store excess energy generated by my solar panels?',
			answer: `Yes, you can store excess energy generated by your solar panels using a battery storage system. This allows you to store excess energy generated during the day for use at night or during power outages.`
		},
		{
			question: 'Are solar panels environmentally friendly?',
			answer: `Yes, solar panels are an environmentally friendly source of energy. They generate electricity without emitting greenhouse gases, pollution, or waste. Additionally, solar panels are made from recyclable materials and can be recycled at the end of their life cycle.`
		},
		{
			question: 'What are some common issues that can affect solar panel performance?',
			answer: `Some common issues that can affect solar panel performance include:\n
- Dirt and debris buildup\n
- Shading from trees or buildings\n
- Loose or faulty connections\n
- Inverter issues\n
- Panel damage or degradation`
		}
	];

	let openIndex: number | null = null;

	function toggle(index: number) {
		openIndex = openIndex === index ? null : index;
	}

	const testimonials = [
		{
			text: `Alliance Power Generation Company has exceeded our expectations in every way. Their solar system has reduced our energy bills by over 50% and their team has been a pleasure to work with. We couldn't be happier with our decision to go solar with Alliance Power Generation Company.`,
			name: 'Funke Johnson ',
			role: 'CEO, TechFlow Inc.',
			initials: 'FJ'
		},
		{
			text: `As a business owner, I am always looking to reduce costs and increase efficiency. Alliance Power Generation Company's solar energy solution has done just that. Their team was professional, knowledgeable and made the installation process seamless. I highly recommend them to any business looking to make the switch to renewable energy.`,
			name: 'Sani Idowu',
			role: 'CEO, Innovate Co.',
			initials: 'SI'
		},
		{
			text: `We were blown away by the level of service and expertise provided by Alliance Power Generation Company. From the initial consultation to the final installation, their team was courteous, professional, and always available to answer our questions. Our new solar energy system is not only saving us money, but it's also giving us peace of mind knowing we're doing our part for the environment. Thank you.`,
			name: 'Clifford Okechukwu',
			role: 'Civil Servant',
			initials: 'CO'
		}
	];
</script>

<svelte:head>
	<title>Alliance Power Generation</title>
	<meta
		name="description"
		content="Projects Completed In Last 3 Years 1 Happy Clients Who Trust Us 10 With a strong focus on research and development, Alliance Power Generation Company has developed cutting-edge solar technologies and solutions that maximize energy production and optimize energy efficiency. Our team..."
	/>
	<meta property="og_title" content="Alliance Power Generation" />
	<meta
		property="og_description"
		content="Projects Completed In Last 3 Years 1 Happy ClientsWho Trust Us 10 With a strong focus on research and development, Alliance Power Generation Company has developed cutting-edge solar technologies and solutions that maximize energy production and optimize energy efficiency. Our team..."
	/>
</svelte:head>
<main class="inter h-screen w-screen overflow-y-auto scroll-smooth">
	<section
		class="grid h-auto min-h-[85vh] w-full grid-cols-1 items-center justify-items-stretch bg-cover bg-center p-20 md:grid-cols-2"
	>
		<img
			src={hero_img}
			alt="Hero"
			class="order-first h-75 w-75 justify-self-center rounded-full object-cover object-center md:order-last md:h-100 md:w-100 md:justify-self-end lg:h-125 lg:w-125"
		/>

		<div class="h-fit w-full space-y-6 justify-self-start">
			<h1
				class="text-3xl leading-tight font-bold text-black md:text-4xl lg:text-5xl lg:leading-relaxed"
			>
				Power Your Business with Clean, Reliable Energy
			</h1>
			<p class="text-lg leading-relaxed text-neutral-500 md:text-xl">
				Scalable renewable generation solutions that cut costs, reduce risk, and future-proof your
				operations.
			</p>
			<button
				type="button"
				class="mt-2 h-16 w-full rounded-4xl border bg-[#3f3e73] text-white transition-transform duration-200 hover:-translate-y-1 hover:bg-[#03a9f4] active:translate-y-px md:w-50"
			>
				Get Quote
			</button>
		</div>
	</section>

	<section class="mt-30 h-auto min-h-130 w-full p-20">
		<h2 class="text-center text-3xl font-semibold tracking-tight">Our Partners</h2>
		<div class="mt-10 grid grid-cols-2 place-items-center md:grid-cols-3 lg:grid-cols-5">
			<img src={taj} alt="Taj Bank" class="h-50 w-50 rounded-full object-contain object-center" />
			<img src={jaiz} alt="Jaiz Bank" class="h-50 w-50 rounded-full object-contain object-center" />
			<img
				src={zamfara}
				alt="Zamfara state government Nigeria"
				class="h-50 w-50 rounded-full object-contain object-center"
			/>
			<img src={crown_club} alt="Crown club and resorts" class="h-50 w-50 rounded-full" />
			<img
				src={glisten}
				alt="Glisten international academy"
				class="h-50 w-50 rounded-full object-contain object-center"
			/>
		</div>
	</section>
	<section class="bg-gray-50 p-20">
		<div class="mx-auto max-w-7xl px-4 text-center sm:px-6 lg:px-8">
			<h2 class="mb-4 text-3xl font-extrabold tracking-tight text-gray-900">
				Power. Efficiency. Sustainability.
			</h2>
			<p class="mb-12 text-gray-600">
				Complete solar solutions that reduce costs, drive sustainability, and put you first.
			</p>

			<div class="grid gap-8 sm:grid-cols-1 md:grid-cols-3">
				<!-- Card 1 -->
				<div
					class="flex flex-col items-center rounded-xl bg-white p-6 text-center shadow-md transition hover:shadow-xl"
				>
					<div class="mb-4 rounded-full bg-yellow-100 p-4">
						<svg
							xmlns="http://www.w3.org/2000/svg"
							width="24"
							height="24"
							viewBox="0 0 24 24"
							fill="none"
							stroke="oklch(79.5% 0.184 86.047)"
							stroke-width="2"
							stroke-linecap="round"
							stroke-linejoin="round"
							class="lucide lucide-sun-icon lucide-sun"
							><circle cx="12" cy="12" r="4" /><path d="M12 2v2" /><path d="M12 20v2" /><path
								d="m4.93 4.93 1.41 1.41"
							/><path d="m17.66 17.66 1.41 1.41" /><path d="M2 12h2" /><path d="M20 12h2" /><path
								d="m6.34 17.66-1.41 1.41"
							/><path d="m19.07 4.93-1.41 1.41" /></svg
						>
					</div>
					<h3 class="mb-2 text-xl font-semibold">Complete Solar Solutions</h3>
					<p class="text-gray-600">
						Design, installation, maintenance, and energy consulting optimized for maximum ROI.
					</p>
				</div>

				<!-- Card 2 -->
				<div
					class="flex flex-col items-center rounded-xl bg-white p-6 text-center shadow-md transition hover:shadow-xl"
				>
					<div class="mb-4 rounded-full bg-green-100 p-4">
						<svg
							xmlns="http://www.w3.org/2000/svg"
							width="24"
							height="24"
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							stroke-width="2"
							stroke-linecap="round"
							stroke-linejoin="round"
							class="lucide lucide-leaf-icon lucide-leaf text-green-500"
							><path
								d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z"
							/><path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12" /></svg
						>
					</div>
					<h3 class="mb-2 text-xl font-semibold">Lower Costs, Greener Future</h3>
					<p class="text-gray-600">
						Cut energy bills, reduce reliance on traditional power, and contribute to a cleaner
						planet.
					</p>
				</div>

				<!-- Card 3 -->
				<div
					class="flex flex-col items-center rounded-xl bg-white p-6 text-center shadow-md transition hover:shadow-xl"
				>
					<div class="mb-4 rounded-full bg-blue-100 p-4">
						<svg
							xmlns="http://www.w3.org/2000/svg"
							width="24"
							height="24"
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							stroke-width="2"
							stroke-linecap="round"
							stroke-linejoin="round"
							class="lucide lucide-headset-icon lucide-headset text-blue-500"
							><path
								d="M3 11h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-5Zm0 0a9 9 0 1 1 18 0m0 0v5a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3Z"
							/><path d="M21 16v2a4 4 0 0 1-4 4h-5" /></svg
						>
					</div>
					<h3 class="mb-2 text-xl font-semibold">Seamless Customer Experience</h3>
					<p class="text-gray-600">
						Expert guidance and support at every step to ensure a smooth, worry-free journey.
					</p>
				</div>
			</div>

			<!-- CTA -->
			<div class="mt-12">
				<a
					href={resolve('/')}
					class="inline-block rounded-4xl bg-[#3f3e73] px-8 py-3 font-semibold text-white shadow-md transition hover:bg-[#03a9f4]"
				>
					Get Started
				</a>
			</div>
		</div>
	</section>

	<section class="mt-40 h-150 w-full space-y-4">
		<h2 class="text-center text-3xl font-semibold tracking-tight">Our Projects</h2>
		<div
			class="flex h-120 w-full snap-x snap-mandatory flex-nowrap items-center gap-3 overflow-x-auto"
		>
			<div
				class="group relative flex h-110 w-120 shrink-0 snap-center flex-col-reverse items-center overflow-hidden rounded-lg bg-cover bg-center p-3 shadow-lg transition-transform hover:scale-[1.02]"
				style={`background-image: url(${taj_bank_kano})`}
			>
				<div
					class="absolute inset-0 bg-linear-to-t from-black/60 via-black/10 to-transparent"
				></div>
				<div
					class="relative z-10 flex h-20 w-[95%] flex-col justify-center rounded-xl bg-white/10 bg-clip-padding px-4 backdrop-blur-sm"
				>
					<h3 class="text-center text-xl font-semibold text-white">Taj Bank Kano</h3>
					<p class="text-center text-base text-white/90">30KVA Solar installation</p>
				</div>
				<button
					class="absolute bottom-28 rounded-full bg-white px-6 py-2 text-sm font-medium text-gray-900 opacity-0 shadow-lg transition-opacity group-hover:opacity-100"
				>
					View Details
				</button>
			</div>

			<div
				class="group relative flex h-110 w-120 shrink-0 snap-center flex-col-reverse items-center overflow-hidden rounded-lg bg-cover bg-center p-3 shadow-lg transition-transform hover:scale-[1.02]"
				style={`background-image: url(${taj_bank_sokoto})`}
			>
				<div
					class="absolute inset-0 bg-linear-to-t from-black/60 via-black/10 to-transparent"
				></div>
				<div
					class="relative z-10 flex h-20 w-[95%] flex-col justify-center rounded-xl bg-white/10 bg-clip-padding px-4 backdrop-blur-sm"
				>
					<h3 class="text-center text-xl font-semibold text-white">Taj Bank Sokoto</h3>
					<p class="text-center text-base text-white/90">Solar installation</p>
				</div>
				<button
					class="absolute bottom-28 rounded-full bg-white px-6 py-2 text-sm font-medium text-gray-900 opacity-0 shadow-lg transition-opacity group-hover:opacity-100"
				>
					View Details
				</button>
			</div>

			<div
				class="group relative flex h-110 w-120 shrink-0 snap-center flex-col-reverse items-center overflow-hidden rounded-lg bg-cover bg-center p-3 shadow-lg transition-transform hover:scale-[1.02]"
				style={`background-image: url(${lakeview_estate})`}
			>
				<div
					class="absolute inset-0 bg-linear-to-t from-black/60 via-black/10 to-transparent"
				></div>
				<div
					class="relative z-10 flex h-20 w-[95%] flex-col justify-center rounded-xl bg-white/10 bg-clip-padding px-4 backdrop-blur-sm"
				>
					<h3 class="text-center text-xl font-semibold text-white">Lakeview Estate</h3>
					<p class="text-center text-base text-white/90">10KVA Solar installation</p>
				</div>
				<button
					class="absolute bottom-28 rounded-full bg-white px-6 py-2 text-sm font-medium text-gray-900 opacity-0 shadow-lg transition-opacity group-hover:opacity-100"
				>
					View Details
				</button>
			</div>

			<div
				class="group relative flex h-110 w-120 shrink-0 snap-center flex-col-reverse items-center overflow-hidden rounded-lg bg-cover bg-center p-3 shadow-lg transition-transform hover:scale-[1.02]"
				style={`background-image: url(${edible_creations})`}
			>
				<div
					class="absolute inset-0 bg-linear-to-t from-black/60 via-black/10 to-transparent"
				></div>
				<div
					class="relative z-10 flex h-20 w-[95%] flex-col justify-center rounded-xl bg-white/10 bg-clip-padding px-4 backdrop-blur-sm"
				>
					<h3 class="text-center text-xl font-semibold text-white">Edible Creations</h3>
					<p class="text-center text-base text-white/90">Commercial Installation</p>
				</div>
				<button
					class="absolute bottom-28 rounded-full bg-white px-6 py-2 text-sm font-medium text-gray-900 opacity-0 shadow-lg transition-opacity group-hover:opacity-100"
				>
					View Details
				</button>
			</div>

			<div
				class="group relative flex h-110 w-120 shrink-0 snap-center flex-col-reverse items-center overflow-hidden rounded-lg bg-cover bg-center p-3 shadow-lg transition-transform hover:scale-[1.02]"
				style={`background-image: url(${crown_club_project})`}
			>
				<div
					class="absolute inset-0 bg-linear-to-t from-black/60 via-black/10 to-transparent"
				></div>
				<div
					class="relative z-10 flex h-20 w-[95%] flex-col justify-center rounded-xl bg-white/10 bg-clip-padding px-4 backdrop-blur-sm"
				>
					<h3 class="text-center text-xl font-semibold text-white">Crown Club</h3>
					<p class="text-center text-base text-white/90">Solar installation</p>
				</div>
				<button
					class="absolute bottom-28 rounded-full bg-white px-6 py-2 text-sm font-medium text-gray-900 opacity-0 shadow-lg transition-opacity group-hover:opacity-100"
				>
					View Details
				</button>
			</div>

			<div
				class="group relative flex h-110 w-120 shrink-0 snap-center flex-col-reverse items-center overflow-hidden rounded-lg bg-cover bg-center p-3 shadow-lg transition-transform hover:scale-[1.02]"
				style={`background-image: url(${mowa_zamfara})`}
			>
				<div
					class="absolute inset-0 bg-linear-to-t from-black/60 via-black/10 to-transparent"
				></div>
				<div
					class="relative z-10 flex h-20 w-[95%] flex-col justify-center rounded-xl bg-white/10 bg-clip-padding px-4 backdrop-blur-sm"
				>
					<h3 class="text-center text-xl font-semibold text-white">
						Ministry of Women Affairs Zamfara Block A
					</h3>
					<p class="text-center text-base text-white/90">108KVA Solar Inverters installation</p>
				</div>
				<button
					class="absolute bottom-28 rounded-full bg-white px-6 py-2 text-sm font-medium text-gray-900 opacity-0 shadow-lg transition-opacity group-hover:opacity-100"
				>
					View Details
				</button>
			</div>

			<div
				class="group relative flex h-110 w-120 shrink-0 snap-center flex-col-reverse items-center overflow-hidden rounded-lg bg-cover bg-center p-3 shadow-lg transition-transform hover:scale-[1.02]"
				style={`background-image: url(${mowa_zamfara2})`}
			>
				<div
					class="absolute inset-0 bg-linear-to-t from-black/60 via-black/10 to-transparent"
				></div>
				<div
					class="relative z-10 flex h-20 w-[95%] flex-col justify-center rounded-xl bg-white/10 bg-clip-padding px-4 backdrop-blur-sm"
				>
					<h3 class="text-center text-xl font-semibold text-white">
						Ministry of Women Affairs Zamfara Block B
					</h3>
					<p class="text-center text-base text-white/90">54KVA Solar Inverters installation</p>
				</div>
				<button
					class="absolute bottom-28 rounded-full bg-white px-6 py-2 text-sm font-medium text-gray-900 opacity-0 shadow-lg transition-opacity group-hover:opacity-100"
				>
					View Details
				</button>
			</div>

			<div
				class="group relative flex h-110 w-120 shrink-0 snap-center flex-col-reverse items-center overflow-hidden rounded-lg bg-cover bg-center p-3 shadow-lg transition-transform hover:scale-[1.02]"
				style={`background-image: url(${glistens_project})`}
			>
				<div
					class="absolute inset-0 bg-linear-to-t from-black/60 via-black/10 to-transparent"
				></div>
				<div
					class="relative z-10 flex h-20 w-[95%] flex-col justify-center rounded-xl bg-white/10 bg-clip-padding px-4 backdrop-blur-sm"
				>
					<h3 class="text-center text-xl font-semibold text-white">
						Glistens International Academy Abuja
					</h3>
					<p class="text-center text-base text-white/90">108KVA Solar Inverters installation</p>
				</div>
				<button
					class="absolute bottom-28 rounded-full bg-white px-6 py-2 text-sm font-medium text-gray-900 opacity-0 shadow-lg transition-opacity group-hover:opacity-100"
				>
					View Details
				</button>
			</div>

			<div
				class="group relative flex h-110 w-120 shrink-0 snap-center flex-col-reverse items-center overflow-hidden rounded-lg bg-cover bg-center p-3 shadow-lg transition-transform hover:scale-[1.02]"
				style={`background-image: url(${great_height})`}
			>
				<div
					class="absolute inset-0 bg-linear-to-t from-black/60 via-black/10 to-transparent"
				></div>
				<div
					class="relative z-10 flex h-20 w-[95%] flex-col justify-center rounded-xl bg-white/10 bg-clip-padding px-4 backdrop-blur-sm"
				>
					<h3 class="text-center text-xl font-semibold text-white">Great Heights Academy Abuja</h3>
					<p class="text-center text-base text-white/90">165KVA Solar Inverters installation</p>
				</div>
				<button
					class="absolute bottom-28 rounded-full bg-white px-6 py-2 text-sm font-medium text-gray-900 opacity-0 shadow-lg transition-opacity group-hover:opacity-100"
				>
					View Details
				</button>
			</div>
		</div>
		<button
			class="mx-auto flex h-12.5 w-40 items-center justify-center rounded-4xl bg-[#3f3e73] text-white transition-colors hover:bg-[#03a9f4]/80"
			type="button">More Projects</button
		>
	</section>

	<section class="mt-50 min-h-screen bg-linear-to-br from-[#3f3e73] to-[#2a294f] px-5 py-16">
		<div class="mx-auto max-w-6xl">
			<header class="mb-16 text-center">
				<h2 class="mb-4 text-3xl font-bold tracking-tight text-white md:text-5xl">
					What Our Customers Say
				</h2>
				<p class="mx-auto max-w-xl text-lg text-white/80">
					Don't just take our word for it. Hear from those who've experienced the difference.
				</p>
			</header>

			<div class="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
				{#each testimonials as t}
					<div
						class="group relative overflow-hidden rounded-2xl bg-white/95 p-8 shadow-xl transition-all duration-300 hover:-translate-y-2 hover:shadow-2xl"
					>
						<div
							class="absolute top-0 left-0 h-1 w-full origin-left scale-x-0 bg-linear-to-r from-[#03a9a4] to-[#29b675] transition-transform duration-300 group-hover:scale-x-100"
						></div>

						<div
							class="mb-5 flex h-12 w-12 items-center justify-center rounded-full bg-linear-to-br from-[#03a9a4] to-[#29b675] text-xl font-bold text-white"
						>
							"
						</div>

						<div class="mb-4 text-[#29b675]">★★★★★</div>

						<p class="mb-6 text-[1.05rem] leading-relaxed text-gray-700 italic">
							{t.text}
						</p>

						<div class="flex items-center gap-4">
							<div
								class="flex h-14 w-14 items-center justify-center rounded-full bg-linear-to-br from-[#3f3e73] to-[#03a9a4] text-lg font-bold text-white"
							>
								{t.initials}
							</div>

							<div>
								<div class="font-semibold text-[#3f3e73]">
									{t.name}
								</div>
								<div class="text-sm text-[#03a9a4]">
									{t.role}
								</div>
							</div>
						</div>
					</div>
				{/each}
			</div>
		</div>
	</section>
	<section class="mx-auto my-24 max-w-3xl px-4">
		<h2 class="mb-10 text-center text-3xl font-semibold text-[#3f3e73]">
			Frequently Asked Questions
		</h2>

		<div class="space-y-4">
			{#each faqs as faq, i}
				<div
					class="group overflow-hidden rounded-xl border border-[#3f3e73]/10 bg-white shadow-sm transition-shadow duration-300 hover:shadow-md"
				>
					<button
						type="button"
						on:click={() => toggle(i)}
						class="flex w-full items-center justify-between gap-4 px-6 py-4 text-left"
					>
						<span
							class="font-medium text-[#3f3e73] transition-colors duration-300 group-hover:text-[#03a9a4]"
						>
							{faq.question}
						</span>

						<span
							class="flex h-8 w-8 items-center justify-center rounded-full bg-[#3f3e73]/10 text-[#3f3e73] transition-all duration-300 group-hover:bg-[#03a9a4] group-hover:text-white"
							class:rotate-45={openIndex === i}
						>
							+
						</span>
					</button>

					{#if openIndex === i}
						<div
							in:slide={{ duration: 250 }}
							out:fade={{ duration: 150 }}
							class="px-6 pb-5 text-sm leading-relaxed text-gray-600"
						>
							{faq.answer}
						</div>
					{/if}
				</div>
			{/each}
		</div>
	</section>
</main>

<style lang="postcss">
	@reference "tailwindcss";
</style>
